gitlabUrl: https://gitlab.infiscale-tech.com
runnerToken: ""

image:
  registry: docker.io
  image: gitlab/gitlab-runner
  tag: alpine-v18.3.1

checkInterval: 3
concurrent: 1
unregisterRunners: true

rbac:
  create: true

serviceAccount:
  create: true

runners:
  config: |
    [[runners]]
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab-ci"
        service_account = "outline-ci-builder"
        service_account_overwrite_allowed = ""
        namespace_overwrite_allowed = ""
        privileged = false
        allow_privilege_escalation = false
        image = "alpine:3.21.3"
        cpu_request = "1"
        cpu_limit = "4"
        memory_request = "2Gi"
        memory_limit = "12Gi"
        ephemeral_storage_request = "30Gi"
        ephemeral_storage_limit = "60Gi"
        poll_timeout = 1200
